name: Auto bump version, build and push

on:
  push:
    branches:
      - main
    paths:
      - "timelimitserver/**"

  workflow_dispatch:

jobs:
  build-ui:
    name: Build UI (amd64)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build UI
        uses: docker/build-push-action@v6
        with:
          context: ./timelimitserver
          file: ./timelimitserver/Dockerfile.ui
          platforms: linux/amd64
          push: false
          outputs: type=local,dest=ui-output

      - name: Upload UI artifact
        uses: actions/upload-artifact@v4
        with:
          name: ui-dist
          path: ui-output/ui/dist


  build-runtime:
    name: Build Runtime (arm64)
    runs-on: ubuntu-latest
    needs: build-ui

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download UI artifact
        uses: actions/download-artifact@v4
        with:
          name: ui-dist
          path: timelimitserver/ui-dist

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push arm64 runtime image
        uses: docker/build-push-action@v6
        with:
          context: ./timelimitserver
          file: ./timelimitserver/Dockerfile
          push: true
          platforms: linux/arm64
          tags: |
            ghcr.io/jeroenlind/timelimitserver:latest